version: "3.8"
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    environment:
      FRONTEND_URI: '_'
    volumes:
      - ./deployments/default.conf:/etc/nginx/conf.d/default.conf:delegated
    command: [ nginx-debug, '-g', 'daemon off;' ]

  frontend:
    build:
      context: client
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    volumes:
      - ./client:/app:delegated
    command: npm start

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "todo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3307:3306"

  backend:
    build:
      context: server/docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - php-fpm
    restart: on-failure
    volumes:
      - ./server/public:/app/public
    ports:
      - "8080:80"


  php-fpm:
    build:
      context: server/docker/php-fpm
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./server:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql-data: {}
