nelmio_api_doc:
    models:
        names:
            - { alias: User, type: App\Entity\User, groups: [ "default" ] }
            - { alias: Task, type: App\Entity\Task, groups: [ "default" ] }

            - alias: UserView
              type: App\Schema\UserView
              groups: [ "default" ]
            - alias: TaskView
              type: App\Schema\TaskView
              groups: [ "default" ]

    documentation:
        servers:
            - url: /
        tags:
            - name: Security
            - name: User
            - name: Task
        info:
            title: Todo App API
            description: |
                Документация API проекта Todo App.
            version: 0.1.0
        externalDocs:
            description: GitHub
            url: https://github.com/Kokov1ch/todo-app

        paths:
            /api/login_check:
                post:
                    security: [ ]
                    tags:
                        - Security
                    summary: Get a JWT and refresh token using login and password
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        login:
                                            example: "admin"
                                            type: string
                                        password:
                                            example: "admin"
                                            type: string
            /api/registration:
                post:
                    security: [ ]
                    tags:
                        - Security
                    summary: Register a new user
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        login:
                                            example: "fedor"
                                            type: string
                                        fio:
                                            example: "Фет Фёдор Сергеевич"
                                            type: string
                                        email:
                                            example: "fedorfet@gmail.com"
                                            type: string
                                        password:
                                            example: "fedorPass"
                                            type: string

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: |
                        #### Может быть получен при помощи команды:
                        ## `php bin/console lexik:jwt:generate-token -c App\\Entity\\User -t <seconds> <login>`
                        #### Пример команды:
                        ## `php bin/console lexik:jwt:generate-token -c App\\Entity\\User -t 86400 admin`
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        disable_default_routes: true
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc