nelmio_api_doc:
    models:
        names:
            - { alias: User, type: App\Entity\User, groups: [ "default" ] }
            - { alias: Task, type: App\Entity\Task, groups: [ "default" ] }

            - alias: UserIdAndFioView
              type: App\Schema\UserView
              groups: [ "id", "fio" ]
            - alias: UserView
              type: App\Schema\UserView
              groups: [ "default" ]
            - alias: TaskView
              type: App\Schema\TaskView
              groups: [ "default" ]

    documentation:
        servers:
            - url: /
        tags:
            - name: User
            - name: Task
        info:
            title: Todo App API
            description: |
                Документация API проекта Todo App.
            version: 0.1.0
        externalDocs:
            description: GitHub
            url: https://github.com/Kokov1ch/todo-app

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: >
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        disable_default_routes: true
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc